# Generated by Django 2.0.1 on 2019-03-27 19:14

from django.db import migrations
import django_tesseract.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_tesseract.widgets.TesseractField(verbose_name='Contenu'),
        ),
    ]
